services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Gie\FacetBundle\Content\Query\Common\FacetBuilderVisitor\TagType:
        tags:
            - {name: ezpublish.search.solr.query.content.facet_builder_visitor}
            - {name: ezpublish.search.solr.query.location.facet_builder_visitor}

    Gie\FacetBundle\Content\Query\Common\FacetBuilderVisitor\CustomDateType:
        tags:
            - {name: ezpublish.search.solr.query.content.facet_builder_visitor}
            - {name: ezpublish.search.solr.query.location.facet_builder_visitor}

    Gie\FacetBundle\Content\Query\Common\FacetBuilderVisitor\SolrFieldType:
        tags:
            - {name: ezpublish.search.solr.query.content.facet_builder_visitor}
            - {name: ezpublish.search.solr.query.location.facet_builder_visitor}

    Gie\FacetBundle\FieldMapper\CustomTagFieldMapper:
        tags:
            - {name: ezpublish.search.solr.field_mapper.content}

    Gie\FacetBundle\FieldMapper\LocationCustomTagFieldMapper:
        tags:
            - {name: ezpublish.search.solr.field_mapper.location}

    Gie\FacetBundle\Content\Search\Helper\ContentTypeFacetSearchHelper:
        tags:
            - {name: gie.facet_search.helper, alias: 'content_type'}

    Gie\FacetBundle\Content\Search\Helper\TagFacetSearchHelper:
        arguments:
            $tagsService: '@eztags.api.service.tags.inner'
        tags:
            - {name: gie.facet_search.helper, alias: 'tags'}

    Gie\FacetBundle\Content\Search\Helper\CustomDateFacetSearchHelper:
        tags:
            - {name: gie.facet_search.helper, alias: 'custom_date'}

    gie.facet_search.solr_field.helper:
        class: Gie\FacetBundle\Content\Search\Helper\SolrFieldSearchHelper
        shared: false
        arguments:
            - '@logger'
        tags:
            - {name: gie.facet_search.helper, alias: 'solr_field'}

    gie.facet.facet_loader:
        public: true
        class: Gie\FacetBundle\Content\Search\Helper\FacetLoader


    Gie\FacetBundle\Content\Search\Helper\FacetSearch:
        arguments:
            $facetLoader: '@gie.facet.facet_loader'

    gie.search.solr.query.common.criterion_visitor.tag_in:
        class: Gie\FacetBundle\Content\Query\Content\CriterionVisitor\TagIn
        arguments:
            - '@eztags.api.service.tags'
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}
            - {name: ezpublish.search.solr.query.location.criterion_visitor}

    gie.search.solr.query.common.criterion_visitor.sorl_field_in:
        class: Gie\FacetBundle\Content\Query\Content\CriterionVisitor\SorlFieldIn
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}
            - {name: ezpublish.search.solr.query.location.criterion_visitor}

    gie.search.solr.query.common.criterion_visitor.custom_date_in:
        class: Gie\FacetBundle\Content\Query\Content\CriterionVisitor\CustomDateIn
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}
            - {name: ezpublish.search.solr.query.location.criterion_visitor}
