<?php

namespace Gie\FacetBundle;

use Gie\FacetBundle\DependencyInjection\Compiler\FacetHelperCompilerPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class GieFacetBundle extends Bundle
{
    public function build( ContainerBuilder $container )
    {
        parent::build( $container ); // TODO: Change the autogenerated stub
        $container->addCompilerPass(new FacetHelperCompilerPass());
    }

}
